---
- hosts: web_proxy
  become: yes
  tasks:
    - name: Ensure EPEL is activated
      yum:
        name: epel-release
        state: latest

    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: latest

    - name: Ensure Nginx service is enabled and started
      service:
        name: nginx
        state: started
        enabled: true

    - name: Update index.html with custom one
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        mode: '0644'
 